defaults: &defaults
  docker:
    - image: cimg/node:lts-browsers

version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - run: yarn --pure-lockfile
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn ci
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v?[0-9]+(\.[0-9]+)*(-(alpha|beta)\.[0-9]+)?/
          requires:
            - test
